name: Merge workflow
on: [ pull_request ]
jobs:
    Test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos, windows-latest ]
        steps: 
            - uses: actions/checkout@v3
            - run: echo "The job was automatically triggered by a a ${{ github.event_name }} event."
            - run: python demo.py
            - run: newman run testars.postman_collection.json